### ISSUE TITLE
Wing stats

### ISSUE THREAD

**Issue by ReCONman259** [abluescarab/tModLoader-WingSlot#28] opened 2018-09-17 18:35 UTC
The wings once added to the wing slot, doesn't add any stats, such as Warding or mencing.

**Comment by abluescarab** [comment] 2018-09-20 02:49
Duplicate of #26. Have you updated to the latest Wing Slot?

**Comment by ReCONman259** [comment] 2018-09-20 09:56
The last time I had this mod installed the issue was there, but now the mod it fixed in that sense. Thank you very much, great mod, adds more options to have more accessories

**Comment by abluescarab** [comment] 2018-09-21 03:33
Thank you for using Wing Slot! I'm glad you like it! Closing issue.

**Closed by abluescarab** 2018-09-21 03:33 UTC
Labels: bug, duplicate

**Comment by Revemohl** [comment] 2018-09-24 21:00
Didn't want to open a new issue because this is directly related to this one. Would it be possible to add a config option for enabling or disabling wing prefixes, then? I've always felt that getting one more modifier thanks to the wing slot was a bit unbalanced, and I thought that the new behavior was intended.
