### ISSUE TITLE
Unable to unequip wings from slot.

### ISSUE THREAD

**Issue by Shadefire** [abluescarab/tModLoader-WingSlot#22] opened 2018-06-24 02:19 UTC
Since today's update of the mod I've been unable to unequip wings from my characters wing slots. I can equip them to vanity and swap them between the two slots, but am unable to remove them. I've checked all possible mods for conflicts and none seem to be the culprit behind the problem. I can however remove dye from the dye slot with no problem if that helps. Other than updating I've not altered anything else.

**Comment by abluescarab** [comment] 2018-06-24 06:01
Thanks for letting me know. I'll put out a hotfix ASAP.

**Comment by abluescarab** [comment] 2018-06-24 06:02
Duplicate of #21. Thanks for letting me know. I'll put out a hotfix ASAP.

**Closed by abluescarab** 2018-06-24 06:02 UTC
