### ISSUE TITLE
Wings dont prevent fall damage

### ISSUE THREAD

**Issue by Technoman21** [abluescarab/tModLoader-WingSlot#4] opened 2016-12-26 22:22 UTC
One thing i noticed while using this mod is that i would take fall damage when i equip the wings in the wing slot. This sucks because i don't want to use a lucky horseshoe up until moonlord incase i die from fall damage. pls fix.

**Comment by homoweirdus** [comment] 2016-12-26 22:29
really? i remember taking no fall damage with wings in the slot

**Comment by homoweirdus** [comment] 2016-12-26 22:31
just tested it and it does prevent fall damage

**Comment by homoweirdus** [comment] 2016-12-26 22:46
did you perhaps shift right click instead of right click and it went into the vanity slot?

**Comment by abluescarab** [comment] 2016-12-27 03:54
I can't replicate this behavior. Did you do what @homoweirdus suggested and shift-right-click instead of just right-clicking?

**Comment by homoweirdus** [comment] 2016-12-27 04:15
the only other thing i can think of is if they equipped some modded wings that dont prevent fall damage and even then i think the fall damage immunity is hard coded

**Comment by Technoman21** [comment] 2016-12-27 06:52
that's weird, maybe i had the wrong version of tmodloader or something. I tested with loki's wings (dev wings) maybe that's the problem

**Comment by Technoman21** [comment] 2016-12-27 06:55
I just tested again, i don't take fall damage now. strange

**Comment by Technoman21** [comment] 2016-12-27 11:28
Okay i found out what was causing it. If you go on a mount. I haven't found out what mounts specifically do this but it might be modded mounts since i was using one (molten collar hound mount from thorium) I think its because it halves fall damage if you were to take it

**Comment by abluescarab** [comment] 2016-12-27 20:51
I'm not sure what to do about that. Can you disable the wing slot mod and equip the wings in a normal accessory slot, then tell me if the collar mount does the same thing? It could either be a problem with the collar mount mod or with my mod. Mod compatibility is an issue that has to be addressed from both parties.

**Comment by MrRapenstien** [comment] 2017-12-03 05:03
i can confirm this happens with vanilla mounts as well

**Comment by abluescarab** [comment] 2019-12-18 01:12
This is a vanilla issue, unfortunately. It's not caused by Wing Slot. Closing this issue.

**Closed by abluescarab** 2019-12-18 01:12 UTC
Labels: further testing needed
